on:
    push:
        branches: 
            - main
    pull_request:
        branches:
            - main

jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: Hello World
              run: echo "Hello World"
